write.csv(data1, "data1", row.names = TRUE)
write.csv(data2, "data2", row.names = TRUE)
write.csv(probPreds1, "probpreds1", row.names = TRUE)
write.csv(probPreds2, "probpreds2", row.names = TRUE)
write.csv(indices1, "indice1", row.names = TRUE)
write.csv(indices2, "indice2", row.names = TRUE)
write.csv(moda, "moda", row.names = TRUE)
write.csv(baixa_conf, "baixa_conf", row.names = TRUE)
write.csv(produto_confianca, "produto_confianca", row.names = TRUE)
write.csv(data_1_it, "probpreds1", row.names = TRUE)
write.csv(data_x_it, "probpreds2", row.names = TRUE)
write.csv(predicao[new,4], "rotulados", row.names = TRUE)
write.csv(data1[sup1,], "treinamento1", row.names = TRUE)
write.csv(data2[sup2,], "treinamento2", row.names = TRUE)
write.csv(data1, "data1", row.names = TRUE)

write.csv(conj_treinamento, "conj_treinamento", row.names = TRUE)
